version: "2.2"

networks:
  mobi-order-processing:
    external:
      name: mobi-order-processing

services:
  discovery-server:
    restart: always
    build: mobi-discovery-server/.
    image: discovery-server
    container_name: discovery-server
    ports:
      - 8761:8761
    networks:
      - mobi-order-processing

  api-gateway:
    restart: always
    build: api-gateway/.
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-server
    ports:
      - 8010:8010
    networks:
      - mobi-order-processing

  inventory-service:
    restart: always
    build: mobi-inventory-service/.
    image: inventory-service
    container_name: inventory-service
    depends_on:
      - discovery-server
    ports:
      - 8081:8081
    networks:
      - mobi-order-processing

  customer-service:
    restart: always
    build: mobi-customer-service/.
    image: customer-service
    container_name: customer-service
    depends_on:
      - discovery-server
    ports:
      - 8083:8083
    networks:
      - mobi-order-processing

  order-service:
    restart: always
    build: mobi-order-service/.
    image: order-service
    container_name: order-service
    depends_on:
      - discovery-server
      - inventory-service
    ports:
      - 8082:8082
    networks:
      - mobi-order-processing

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=mobi-order-processing-db
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - mobi-order-processing

volumes:
  postgres-db:
