spring:
  application:
    name: api-gateway

server:
  port: 8010

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

zuul:
  routes:
    inventory-service:
      path: /inventory-service/**
      serviceId: inventory-service

management:
  security:
    enabled: false

logging:
  level:
    com.service.apigateway: DEBUG
